### ISSUE TITLE
Update Package To Use New API

### ISSUE THREAD

**Issue by joefitzgerald** [atom/autocomplete-emojis#1]
Please:
- Don't depend on autocomplete-plus in your package.json
- Switch to using an editor instead of an editorView during registration

Updated example: https://github.com/atom-community/autocomplete-plus/wiki/Tutorial:-Registering-and-creating-a-suggestion-provider

**Comment by eqot** [comment]
Thank you very much for the information!
I am going to update this package accordingly and shortly.
