### ISSUE TITLE
Doesn't work on files with custom syntax.

### ISSUE THREAD

**Issue by danielcgold** [atom/autocomplete-emojis#11]
Emoji autocomplete doesn't work on custom syntax'd slim and scss templates. Tried adding the extension to the settings file in this package with no luck. 

Also not sure if this is an issue for this package or the custom syntax package.

**Comment by eqot** [comment]
I have just published v2.4.1 which works on slim file.
Is this what you want?

Regarding scss, would like like to use emoji in scss? Do you have any examples?

**Comment by danielcgold** [comment]
sweet thanks!

re: scss, yea maybe like:

```
.selector {
  content: '🍔';
 ...
}
```

or

```
.hamburger {
  visibility: visibile; // 🍔 hamburgers are better when you can see them
}
```

**Comment by eqot** [comment]
Sorry for late reply.

I believe that this package works for those examples as you expected like followings since it is enabled in strings and comments in any files.
![emojis-for-sess](https://db.tt/7wHiN8uP)
![emojis-for-sess-2](https://db.tt/T9qXeWy7)

**Comment by eqot** [comment]
Hi @danielcgold ,

Any feedback?

**Comment by danielcgold** [comment]
I stopped using this extension in favor (Rocket)[http://matthewpalmer.net/rocket/]. Thanks for following up!
