### ISSUE TITLE
OSX :warning shown as a blank square

### ISSUE THREAD

**Issue by n70n10** [atom/autocomplete-emojis#13]
OSX :warning shown as a blank square, copying and pasting the emoji to text mate show the correct image
<img width="375" alt="screen shot 2016-06-21 at 19 58 42" src="https://cloud.githubusercontent.com/assets/671211/16242557/d718a8bc-37ea-11e6-8a9b-e8676befe8d7.png">
<img width="86" alt="screen shot 2016-06-21 at 20 01 01" src="https://cloud.githubusercontent.com/assets/671211/16242586/fa5227a4-37ea-11e6-97c2-c91bb244bc17.png">

**Comment by n70n10** [comment]
It shows correctly once I set a font family in atom settings

**Comment by eqot** [comment]
Glad to hear that you could manage it. 👍
