### ISSUE TITLE
Not selecting markdown grammars

### ISSUE THREAD

**Issue by avonmoll** [atom/autocomplete-emojis#16]
For some reason, the package is not activating for markdown grammars. I normally use the `language-pfm` package which overrides the `source.gfm` scope name. `autocomplete-emojis` doesn't activate even when I disable `language-pfm` and activate `language-gfm`. I verified the scope name is correct by opening a MD document ("Pandoc Markdown" shows in the bottom right corner) and typing the following into the devtools console:

```
textEditor = atom.workspace.getActiveTextEditor()
textEditor.getGrammar()
```

Which outputs:

```
Grammar {registry: GrammarRegistry, name: "Pandoc Markdown", fileTypes: Array[9], scopeName: "source.gfm", foldingStopMarker: undefined…}
```

**Comment by eqot** [comment]
Would you like to use this autocomplete for Pandoc Markdown documents?
I can add "*.pmd" to the scope which makes sense.

**Comment by avonmoll** [comment]
I discovered, long after I submitted this issue, that the root cause is with autocomplete-plus itself. See https://github.com/atom/autocomplete-plus/issues/824 for details. As of now, it still hasn't been resolved.

**Comment by eqot** [comment]
Thank you very much for the information.
I did not know the issue in autocomplete-plus.
