### ISSUE TITLE
Update Package To Use New autocomplete-plus API

### ISSUE THREAD

**Issue by joefitzgerald** [atom/autocomplete-emojis#2]
Please:
- Switch to the new `autocomplete-plus` API: https://github.com/atom-community/autocomplete-plus/wiki/Provider-API
- Move away from having 1 provider instance for every editor instance

**Comment by joefitzgerald** [comment]
The old autocomplete-plus API will be removed on Tuesday, February 10th. Please update the API prior to that date, or let me know if you have issues meeting that timeline.

**Comment by eqot** [comment]
Sorry that I did not focus to this but thank you very much for heading up.
I am going to update my package during this weekend.

**Comment by eqot** [comment]
@joefitzgerald, let me check one thing about the wiki page of [Autocomplete Providers](https://github.com/atom-community/autocomplete-plus/wiki/Autocomplete-Providers).

Currently this autocomplete-emojis is listed in the 'Packages That Claim Autocomplete, But Are Not API 1.0.0 Compatible' category, but this has already used the new API. So I would like to update the wiki page for autocomplete-emojis to be listed in 'Providers Not Tied To A Specific Grammar' category.

Do you have any plan to update the wiki page (probably, for other providers as well)?
Or, can I update it by myself?
